version: '3'
services:
  bldns1:
    image: neomediatech/rbldns-static 
    container_name: bldns1
    hostname: bldns1
    restart: 
      always
    networks:
      default:
        ipv4_address: 172.16.1.254/24
  
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24